CREATE DATABASE burgers_db;


USE burgers_db;


CREATE TABLE burgers (
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  
  burger_Name VARCHAR(30) NOT NULL,

  devoured BOOLEAN DEFAULT false,
 

  PRIMARY KEY (id)
);

ALTER TABLE burgers ADD `lastUpdated` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;